#  proxy_cache_bypass $cookie_BRCMWASSOCookie;
#  proxy_cache_bypass $cookie_BRCMAuthHeader;
#  proxy_cache_bypass $cookie_BRCMportalCookie;
  
#  proxy_no_cache $cookie_BRCMWASSOCookie;
#  proxy_no_cache $cookie_BRCMAuthHeader;
#  proxy_no_cache $cookie_BRCMportalCookie;
  
#  proxy_cache_bypass $nocache;
#  proxy_no_cache $nocache;
  
#  proxy_cache_bypass $http_no_store;
#  proxy_no_cache $http_no_store;

#  add_header bc_no-store $http_no_store; 
  
#  proxy_cache_key $host$uri$is_args$args;
#  proxy_cache meta_cache;
#  proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
#  proxy_cache_valid 200 302 3m;
#  proxy_cache_valid 404 502 503 504 500 5s;
  add_header X-Cache-Status $upstream_cache_status;
  
  #add_header bc_ip $remote_addr; 
  proxy_set_header bc_ip $remote_addr;  
  #add_header bc_cip $http_x_forwarded_for; 
  proxy_set_header bc_cip $http_x_forwarded_for; 
  
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_redirect off;
  proxy_buffering on;

  proxy_cookie_path ~^/.*$ /;
