  #add_header bc_ip $remote_addr; 
  proxy_set_header bc_ip $remote_addr;  
  #add_header bc_cip $http_x_forwarded_for; 
  proxy_set_header bc_cip $http_x_forwarded_for; 
  
  #add_header X-Cache-Status $upstream_cache_status;
  add_header App-Cache-Status $upstream_cache_status;

  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_redirect off;
  proxy_buffering on;

  proxy_cookie_path ~^/.*$ /;
