rewrite ^/pages/ru/(.*)$ https://$http_host/pages/en/$1 permanent; 
rewrite ^/pages/cn/(.*)$ https://$http_host/pages/en/$1 permanent;
rewrite ^/pages/de/(.*)$ https://$http_host/pages/en/$1 permanent; 
rewrite ^/pages/kr/(.*)$ https://$http_host/pages/en/$1 permanent; 
rewrite ^/pages/tw/(.*)$ https://$http_host/pages/en/$1 permanent; 
rewrite ^/pages/jp/(.*)$ https://$http_host/pages/en/$1 permanent;
