rewrite ^/pages/corporate/investor_communications/(.*) http://investors.broadcom.com/phoenix.zhtml?c=203541&p=irol-IRHome permanent; 
rewrite ^/pages/corporate/awards/ https://$http_host/company/news/ permanent; 
rewrite ^/pages/contact/request_tech_support/ https://$http_host/support/request-tech-support permanent; 
rewrite ^/pages/contact/regional_tech_response_centers/ https://$http_host/support/regional-tech-response-centers permanent; 
rewrite ^/pages/careers$ https://$http_host/company/careers/ permanent; 
rewrite ^/pages/buy_from_an_authorized_distributor/$ https://$http_host/how-to-buy/#distributors permanent; 
rewrite ^/pages/avago_illumination_solutions_mid_power_leds/$ https://$http_host/support/resources/video-webinar-library permanent; 
rewrite ^/pages/avago_housed_and_kit_encoder_technology/$ https://$http_host/support/resources/video-webinar-library permanent;

rewrite ^/pages/us_digital_housed_encoders_cross_reference https://$http_host/products/motion-control-encoders/housed-encoders/ permanent;

rewrite ^/pages/support/lead_pb-free_and_rohs/rf_and_microwave/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/optocoupler/$ https://$http_host/company/citizenship/quality permanent;
 rewrite ^/pages/support/lead_pb-free_and_rohs/optical_navigation/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/motion_control/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/led/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/identity_lead_free_parts/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/fiber_optics/$ https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/support/lead_pb-free_and_rohs/ask_our_lead-free_experts https://$http_host/company/citizenship/quality permanent; 
rewrite ^/pages/sitemap/ https://$http_host/sitemap permanent; 
rewrite ^/pages/resources/white_papers/$ https://$http_host/support/resources/doc-library permanent; 
rewrite ^/pages/purchase/order_samples/$ https://$http_host/how-to-buy/ permanent;
 rewrite ^/pages/products/adsmodeling/ https://$http_host/ permanent; 
rewrite ^/pages/products$ https://$http_host/products/ permanent; 
rewrite ^/pages/pof/automotive_polymer_optical_fiber_bidirectional_byteflight/ https://$http_host/products/ permanent; 
rewrite ^/pages/parametricsearch/$ https://$http_host/sitemap-products permanent; 
rewrite ^/pages/news/worldwide_press_relations/ https://$http_host/contact/worldwide-press-relations permanent;
 rewrite ^/pages/home$ https://$http_host/ permanent; 
