location ~ ^/(downloads) {

  location ~* \.(?!(html|htm)) {

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Authorization '';
    include /etc/nginx/redirects/general-security-header.conf;

    proxy_set_header Host DOCSBUCKET.s3-website-REGION.amazonaws.com;

    proxy_hide_header x-amz-id-2;
    proxy_hide_header x-amz-request-id;
    proxy_hide_header x-amz-meta-server-side-encryption;
    proxy_hide_header x-amz-server-side-encryption;
    proxy_hide_header Etag;
    proxy_hide_header Server;
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;
    add_header Content-Disposition "inline";
    add_header Content-Type "application/octet-stream";
    add_header X-Cache-Status $upstream_cache_status;

    proxy_pass http://DOCSBUCKET.s3-website-REGION.amazonaws.com;
  }

}

location ~ ^/(vmhtmldocs) {

  #set $envtype "dev";
  #  proxy_cache            s3_cache;
  proxy_http_version 1.1;
  proxy_set_header Connection "";
  proxy_set_header Authorization '';
  #   proxy_set_header       Host ichabod-{{envtype}}-static.s3-website-us-east-1.amazonaws.com;
  proxy_set_header Host DOCSBUCKET.s3-website-REGION.amazonaws.com;
  proxy_hide_header x-amz-id-2;
  proxy_hide_header x-amz-request-id;
  proxy_hide_header x-amz-meta-server-side-encryption;
  proxy_hide_header x-amz-server-side-encryption;
  proxy_hide_header Set-Cookie;
  proxy_ignore_headers Set-Cookie;
  proxy_cache_revalidate on;
  proxy_intercept_errors on;
  proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
  proxy_cache_lock on;
  add_header Cache-Control max-age=31536000;
  add_header X-Cache-Status $upstream_cache_status;
  #add_header Content-Disposition "attachment";
  include /etc/nginx/redirects/general-security-header.conf;

  #proxy_pass http://dev-avagodocs.s3-website-us-west-2.amazonaws.com;
  proxy_pass http://DOCSBUCKET.s3-website-REGION.amazonaws.com;

}