map $http_host $brcmdocsserver {

  "brcm-cs-dev-docs.aws.broadcom.com"     "brcm-cs-dev-docs.aws.broadcom.com";
	"brcm-cs-qa-docs.aws.broadcom.com"      "brcm-cs-qa-docs.aws.broadcom.com";
	"brcm-cs-stg-docs.aws.broadcom.com"     "brcm-cs-stg-docs.aws.broadcom.com";
	"brcm-cs-prd-docs.aws.broadcom.com"     "brcm-cs-prd-docs.aws.broadcom.com";
  "brcm-cs-dr-docs.aws.broadcom.com"      "brcm-cs-dr-docs.aws.broadcom.com";


#  "docs.broadcom.com"         "docs.broadcom.com";
#	"docs.aws.broadcom.com"        "docs.aws.broadcom.com";
#	"docscmsstaging.broadcom.com"     "docscmsstaging.broadcom.com";

}