server {
  client_max_body_size 4G;

  root /var/www/html;

    location ~ ^/(cmsel) {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_connect_timeout       3000;
      proxy_send_timeout          3000;
      proxy_read_timeout          3000;
      send_timeout                3000;
      proxy_pass http://cmseventlistener;
    }

      location = /hc {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_buffering off;
      proxy_pass http://cmseventlistener;
    }


}
upstream cmseventlistener {

   server unix:/tmp/example_1.sock fail_timeout=0;
   server unix:/tmp/example_2.sock fail_timeout=0;
   server unix:/tmp/example_3.sock fail_timeout=0;
   server unix:/tmp/example_4.sock fail_timeout=0;

}
