proxy_cache_path  /var/www/cache  levels=1:2    keys_zone=s3_cache:10m inactive=24h  max_size=1g;


server {
  client_max_body_size 4G;

  #server_name cmsgatewayapp.com;
  root /var/www/html;

  location = /hc {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://cmsgatewayapp;
  }

  location ~ ^/(data|gallery|api|hc) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Last-Modified "Tue, 03 Apr 2018 00:00:00 GMT";
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://cmsgatewayapp;
  }

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://nodeapp;
  }

  location ~* \.(jpg|jpeg|gif|png|bmp|ico|pdf|doc|docx|zip|txt|tgz) {
    try_files $uri @s3;
  }

  location ^~ /img {
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Last-Modified "Tue, 03 Apr 2018 00:00:00 GMT";
    proxy_redirect off;
    proxy_buffering off;
    proxy_pass http://nodeapp;
  }

    location /s3/ {
      proxy_http_version     1.1;
      proxy_set_header       Connection "";
      proxy_set_header       Authorization '';
      proxy_set_header       Host yanpy.dev.s3.amazonaws.com;
      proxy_hide_header      x-amz-id-2;
      proxy_hide_header      x-amz-request-id;
      proxy_hide_header      x-amz-meta-server-side-encryption;
      proxy_hide_header      x-amz-server-side-encryption;
      proxy_hide_header      Set-Cookie;
      proxy_ignore_headers   Set-Cookie;
      proxy_intercept_errors on;
      add_header             Cache-Control max-age=31536000;
      proxy_pass             http://ichabod-qa-static.s3-website-us-east-1.amazonaws.com;
    }

    location @s3{
      proxy_cache            s3_cache;
      proxy_http_version     1.1;
      proxy_set_header       Connection "";
      proxy_set_header       Authorization '';
      proxy_set_header       Host ichabod-qa-static.s3-website-us-east-1.amazonaws.com;
      proxy_hide_header      x-amz-id-2;
      proxy_hide_header      x-amz-request-id;
      proxy_hide_header      x-amz-meta-server-side-encryption;
      proxy_hide_header      x-amz-server-side-encryption;
      proxy_hide_header      Set-Cookie;
      proxy_ignore_headers   Set-Cookie;
      proxy_cache_revalidate on;
      proxy_intercept_errors on;
      proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;
      proxy_cache_lock       on;
      add_header             Cache-Control max-age=31536000;
      add_header             X-Cache-Status $upstream_cache_status;
      proxy_pass             http://ichabod-qa-static.s3-website-us-east-1.amazonaws.com;
    }
}

upstream cmsgatewayapp {
   server unix:/tmp/example_1.sock fail_timeout=0;
   server unix:/tmp/example_2.sock fail_timeout=0;
   server unix:/tmp/example_3.sock fail_timeout=0;
   server unix:/tmp/example_4.sock fail_timeout=0;

}

upstream nodeapp{
    server localhost:3000;
}




