
# This is /cs included in www.broadcom.com host file
#location /cs { 
#rewrite ^/cs/CatalogManager* https://$http_host/pages/404 redirect; 
#rewrite ^/cs/TreeManager https://$http_host/pages/404 redirect;
#rewrite ^/cs/DebugServer https://$http_host/pages/404 redirect;
#rewrite ^/cs/CacheServer https://$http_host/pages/404 redirect; 
#rewrite ^/cs/Inventory https://$http_host/pages/404 redirect; 
#rewrite ^/cs/PageDispatcherServer https://$http_host/pages/404 redirect; 
#rewrite ^/cs/DispatchManager https://$http_host/pages/404 redirect; 
#rewrite ^/cs/SyncSeedDispatchServer https://$http_host/pages/404 redirect;
#rewrite ^/cs/SeedDispatchServer https://$http_host/pages/404 redirect; 
#rewrite ^/cs/FlushServer https://$http_host/pages/404 redirect; 
#rewrite ^/cs/HelloCS https://$http_host/pages/404 redirect; 
#} 

#copied to new file /etc/nginx/redirects/redirects_group_pages.conf
#location /pages { 
rewrite ^/pages/ru/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/cn/(.*)$ https://$http_host/pages/en/$1 redirect;
 rewrite ^/pages/de/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/kr/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/tw/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/jp/(.*)$ https://$http_host/pages/en/$1 redirect;
# } 

# This location / is used in proxying.conf
#location / { 
#if ($http_user_agent ~ "CovarioCSE"){ 
#return 403;
# }
# if ($http_user_agent ~ "Netsparker"){ 
#return 403; 
#} 
#if ($http_user_agent ~ "CovarioCSE"){
# return 403;
# } 
#if ($http_user_agent ~ "heritrix/3.3.0-SNAPSHOT-20150302-2206"){ 
#return 403;
# }
# if ($query_string ~ "\?\?"){
# return 403; 
#} 
#if ($query_string ~ "\?(.*)\?(.*)"){ 
#return 403;
# }
# if ($query_string ~ "^pagename=Support/Home"){
#rewrite ^/cs/Satellite(.*)$ https://$http_host/? redirect; 
#}


