rewrite ^/pages/ru/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/cn/(.*)$ https://$http_host/pages/en/$1 redirect;
rewrite ^/pages/de/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/kr/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/tw/(.*)$ https://$http_host/pages/en/$1 redirect; 
rewrite ^/pages/jp/(.*)$ https://$http_host/pages/en/$1 redirect;
