

rewrite ^/company/contact/sales https://$http_host/company/contact/ redirect;
rewrite ^/company/contact/locations https://$http_host/company/contact/ redirect;
rewrite ^/company/contact/manufacturing https://$http_host/company/contact/ redirect;
rewrite ^/company/contact/media-contacts https://$http_host/company/contact/ redirect; 
rewrite ^/company/contact-us/avago-sales-office https://$http_host/how-to-buy/ redirect; 
rewrite ^/company/about-us/executives/michael-e-hurlston https://$http_host/company/about-us/executives/ redirect; 
rewrite ^/company/about-us/executives/michael-e-hurlston/ https://$http_host/company/about-us/executives/ redirect;
rewrite ^/company/leadership https://$http_host/company/about-us/executives/ redirect;
rewrite ^/company/timeline/$ https://$http_host/company/about-us/company-history redirect; 
rewrite ^/company/leadership/$ https://$http_host/company/about-us/executives/ redirect; 
rewrite ^/company/blog/(.*)$ https://$http_host/blog/$1 redirect; 
rewrite ^/company/$ https://$http_host/company/about-us/ redirect;


